
export type Achievement = {
  id: string;
  name: string;
  description: string;
  icon: string;
  category: string;
  color: string;
  score: number;
  maxProgress: number;
  conditionType: string;
  target: number;
};

export const ACHIEVEMENTS: Achievement[] = [
  {
    "id": "ach_1",
    "name": "Cinephile I",
    "description": "Reach 1 total items logged.",
    "icon": "Film",
    "category": "Milestones",
    "color": "hsl(0, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "total_watches",
    "target": 1
  },
  {
    "id": "ach_2",
    "name": "Cinephile II",
    "description": "Reach 10 total items logged.",
    "icon": "Film",
    "category": "Milestones",
    "color": "hsl(0, 80%, 60%)",
    "score": 50,
    "maxProgress": 10,
    "conditionType": "total_watches",
    "target": 10
  },
  {
    "id": "ach_3",
    "name": "Cinephile III",
    "description": "Reach 50 total items logged.",
    "icon": "Film",
    "category": "Milestones",
    "color": "hsl(0, 80%, 60%)",
    "score": 150,
    "maxProgress": 50,
    "conditionType": "total_watches",
    "target": 50
  },
  {
    "id": "ach_4",
    "name": "Cinephile IV",
    "description": "Reach 100 total items logged.",
    "icon": "Film",
    "category": "Milestones",
    "color": "hsl(0, 80%, 60%)",
    "score": 500,
    "maxProgress": 100,
    "conditionType": "total_watches",
    "target": 100
  },
  {
    "id": "ach_5",
    "name": "Cinephile V",
    "description": "Reach 250 total items logged.",
    "icon": "Film",
    "category": "Milestones",
    "color": "hsl(0, 80%, 60%)",
    "score": 1500,
    "maxProgress": 250,
    "conditionType": "total_watches",
    "target": 250
  },
  {
    "id": "ach_6",
    "name": "Couch Potato I",
    "description": "Reach 1 tv shows logged.",
    "icon": "Tv",
    "category": "Milestones",
    "color": "hsl(24, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "tv_watches",
    "target": 1
  },
  {
    "id": "ach_7",
    "name": "Couch Potato II",
    "description": "Reach 5 tv shows logged.",
    "icon": "Tv",
    "category": "Milestones",
    "color": "hsl(24, 80%, 60%)",
    "score": 50,
    "maxProgress": 5,
    "conditionType": "tv_watches",
    "target": 5
  },
  {
    "id": "ach_8",
    "name": "Couch Potato III",
    "description": "Reach 20 tv shows logged.",
    "icon": "Tv",
    "category": "Milestones",
    "color": "hsl(24, 80%, 60%)",
    "score": 150,
    "maxProgress": 20,
    "conditionType": "tv_watches",
    "target": 20
  },
  {
    "id": "ach_9",
    "name": "Couch Potato IV",
    "description": "Reach 50 tv shows logged.",
    "icon": "Tv",
    "category": "Milestones",
    "color": "hsl(24, 80%, 60%)",
    "score": 500,
    "maxProgress": 50,
    "conditionType": "tv_watches",
    "target": 50
  },
  {
    "id": "ach_10",
    "name": "Couch Potato V",
    "description": "Reach 100 tv shows logged.",
    "icon": "Tv",
    "category": "Milestones",
    "color": "hsl(24, 80%, 60%)",
    "score": 1500,
    "maxProgress": 100,
    "conditionType": "tv_watches",
    "target": 100
  },
  {
    "id": "ach_11",
    "name": "Silver Screen I",
    "description": "Reach 1 movies logged.",
    "icon": "Film",
    "category": "Milestones",
    "color": "hsl(48, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "movie_watches",
    "target": 1
  },
  {
    "id": "ach_12",
    "name": "Silver Screen II",
    "description": "Reach 10 movies logged.",
    "icon": "Film",
    "category": "Milestones",
    "color": "hsl(48, 80%, 60%)",
    "score": 50,
    "maxProgress": 10,
    "conditionType": "movie_watches",
    "target": 10
  },
  {
    "id": "ach_13",
    "name": "Silver Screen III",
    "description": "Reach 50 movies logged.",
    "icon": "Film",
    "category": "Milestones",
    "color": "hsl(48, 80%, 60%)",
    "score": 150,
    "maxProgress": 50,
    "conditionType": "movie_watches",
    "target": 50
  },
  {
    "id": "ach_14",
    "name": "Silver Screen IV",
    "description": "Reach 100 movies logged.",
    "icon": "Film",
    "category": "Milestones",
    "color": "hsl(48, 80%, 60%)",
    "score": 500,
    "maxProgress": 100,
    "conditionType": "movie_watches",
    "target": 100
  },
  {
    "id": "ach_15",
    "name": "Silver Screen V",
    "description": "Reach 250 movies logged.",
    "icon": "Film",
    "category": "Milestones",
    "color": "hsl(48, 80%, 60%)",
    "score": 1500,
    "maxProgress": 250,
    "conditionType": "movie_watches",
    "target": 250
  },
  {
    "id": "ach_true_reviewer",
    "name": "True Reviewer",
    "description": "Write a review.",
    "icon": "MessageSquare",
    "category": "Interactions",
    "color": "hsl(180, 80%, 50%)",
    "score": 50,
    "maxProgress": 1,
    "conditionType": "reviews",
    "target": 1
  },
  {
    "id": "ach_dir_nolan",
    "name": "Time is Relative",
    "description": "Complete the Christopher Nolan Director Journey.",
    "icon": "Award",
    "category": "Director Journeys",
    "color": "hsl(210, 80%, 60%)",
    "score": 1000,
    "maxProgress": 19,
    "conditionType": "dir_nolan",
    "target": 19
  },
  {
    "id": "ach_dir_tarantino",
    "name": "Written and Directed by",
    "description": "Complete the Quentin Tarantino Director Journey.",
    "icon": "Award",
    "category": "Director Journeys",
    "color": "hsl(0, 80%, 50%)",
    "score": 1000,
    "maxProgress": 15,
    "conditionType": "dir_tarantino",
    "target": 15
  },
  {
    "id": "ach_dir_spielberg",
    "name": "Movie Magic",
    "description": "Complete the Steven Spielberg Director Journey.",
    "icon": "Award",
    "category": "Director Journeys",
    "color": "hsl(280, 80%, 60%)",
    "score": 1500,
    "maxProgress": 46,
    "conditionType": "dir_spielberg",
    "target": 46
  },
  {
    "id": "ach_16",
    "name": "The Critic I",
    "description": "Reach 1 written reviews.",
    "icon": "PenTool",
    "category": "Ratings & Reviews",
    "color": "hsl(72, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "reviews",
    "target": 1
  },
  {
    "id": "ach_17",
    "name": "The Critic II",
    "description": "Reach 5 written reviews.",
    "icon": "PenTool",
    "category": "Ratings & Reviews",
    "color": "hsl(72, 80%, 60%)",
    "score": 50,
    "maxProgress": 5,
    "conditionType": "reviews",
    "target": 5
  },
  {
    "id": "ach_18",
    "name": "The Critic III",
    "description": "Reach 20 written reviews.",
    "icon": "PenTool",
    "category": "Ratings & Reviews",
    "color": "hsl(72, 80%, 60%)",
    "score": 150,
    "maxProgress": 20,
    "conditionType": "reviews",
    "target": 20
  },
  {
    "id": "ach_19",
    "name": "The Critic IV",
    "description": "Reach 50 written reviews.",
    "icon": "PenTool",
    "category": "Ratings & Reviews",
    "color": "hsl(72, 80%, 60%)",
    "score": 500,
    "maxProgress": 50,
    "conditionType": "reviews",
    "target": 50
  },
  {
    "id": "ach_20",
    "name": "The Critic V",
    "description": "Reach 100 written reviews.",
    "icon": "PenTool",
    "category": "Ratings & Reviews",
    "color": "hsl(72, 80%, 60%)",
    "score": 1500,
    "maxProgress": 100,
    "conditionType": "reviews",
    "target": 100
  },
  {
    "id": "ach_21",
    "name": "Masterpiece Hunter I",
    "description": "Reach 1 10/10 ratings given.",
    "icon": "Heart",
    "category": "Ratings & Reviews",
    "color": "hsl(96, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "ten_stars",
    "target": 1
  },
  {
    "id": "ach_22",
    "name": "Masterpiece Hunter II",
    "description": "Reach 5 10/10 ratings given.",
    "icon": "Heart",
    "category": "Ratings & Reviews",
    "color": "hsl(96, 80%, 60%)",
    "score": 50,
    "maxProgress": 5,
    "conditionType": "ten_stars",
    "target": 5
  },
  {
    "id": "ach_23",
    "name": "Masterpiece Hunter III",
    "description": "Reach 20 10/10 ratings given.",
    "icon": "Heart",
    "category": "Ratings & Reviews",
    "color": "hsl(96, 80%, 60%)",
    "score": 150,
    "maxProgress": 20,
    "conditionType": "ten_stars",
    "target": 20
  },
  {
    "id": "ach_24",
    "name": "Masterpiece Hunter IV",
    "description": "Reach 50 10/10 ratings given.",
    "icon": "Heart",
    "category": "Ratings & Reviews",
    "color": "hsl(96, 80%, 60%)",
    "score": 500,
    "maxProgress": 50,
    "conditionType": "ten_stars",
    "target": 50
  },
  {
    "id": "ach_25",
    "name": "Masterpiece Hunter V",
    "description": "Reach 100 10/10 ratings given.",
    "icon": "Heart",
    "category": "Ratings & Reviews",
    "color": "hsl(96, 80%, 60%)",
    "score": 1500,
    "maxProgress": 100,
    "conditionType": "ten_stars",
    "target": 100
  },
  {
    "id": "ach_26",
    "name": "Tough Crowd I",
    "description": "Reach 1 1/10 ratings given.",
    "icon": "ThumbsDown",
    "category": "Ratings & Reviews",
    "color": "hsl(120, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "one_stars",
    "target": 1
  },
  {
    "id": "ach_27",
    "name": "Tough Crowd II",
    "description": "Reach 5 1/10 ratings given.",
    "icon": "ThumbsDown",
    "category": "Ratings & Reviews",
    "color": "hsl(120, 80%, 60%)",
    "score": 50,
    "maxProgress": 5,
    "conditionType": "one_stars",
    "target": 5
  },
  {
    "id": "ach_28",
    "name": "Tough Crowd III",
    "description": "Reach 10 1/10 ratings given.",
    "icon": "ThumbsDown",
    "category": "Ratings & Reviews",
    "color": "hsl(120, 80%, 60%)",
    "score": 150,
    "maxProgress": 10,
    "conditionType": "one_stars",
    "target": 10
  },
  {
    "id": "ach_29",
    "name": "Tough Crowd IV",
    "description": "Reach 25 1/10 ratings given.",
    "icon": "ThumbsDown",
    "category": "Ratings & Reviews",
    "color": "hsl(120, 80%, 60%)",
    "score": 500,
    "maxProgress": 25,
    "conditionType": "one_stars",
    "target": 25
  },
  {
    "id": "ach_30",
    "name": "Tough Crowd V",
    "description": "Reach 50 1/10 ratings given.",
    "icon": "ThumbsDown",
    "category": "Ratings & Reviews",
    "color": "hsl(120, 80%, 60%)",
    "score": 1500,
    "maxProgress": 50,
    "conditionType": "one_stars",
    "target": 50
  },
  {
    "id": "ach_31",
    "name": "Night Owl I",
    "description": "Reach 1 items logged between midnight and 4 am.",
    "icon": "Moon",
    "category": "Activity",
    "color": "hsl(144, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "night_watches",
    "target": 1
  },
  {
    "id": "ach_32",
    "name": "Night Owl II",
    "description": "Reach 5 items logged between midnight and 4 am.",
    "icon": "Moon",
    "category": "Activity",
    "color": "hsl(144, 80%, 60%)",
    "score": 50,
    "maxProgress": 5,
    "conditionType": "night_watches",
    "target": 5
  },
  {
    "id": "ach_33",
    "name": "Night Owl III",
    "description": "Reach 15 items logged between midnight and 4 am.",
    "icon": "Moon",
    "category": "Activity",
    "color": "hsl(144, 80%, 60%)",
    "score": 150,
    "maxProgress": 15,
    "conditionType": "night_watches",
    "target": 15
  },
  {
    "id": "ach_34",
    "name": "Night Owl IV",
    "description": "Reach 30 items logged between midnight and 4 am.",
    "icon": "Moon",
    "category": "Activity",
    "color": "hsl(144, 80%, 60%)",
    "score": 500,
    "maxProgress": 30,
    "conditionType": "night_watches",
    "target": 30
  },
  {
    "id": "ach_35",
    "name": "Night Owl V",
    "description": "Reach 50 items logged between midnight and 4 am.",
    "icon": "Moon",
    "category": "Activity",
    "color": "hsl(144, 80%, 60%)",
    "score": 1500,
    "maxProgress": 50,
    "conditionType": "night_watches",
    "target": 50
  },
  {
    "id": "ach_36",
    "name": "Early Bird I",
    "description": "Reach 1 items logged between 5 am and 9 am.",
    "icon": "Sun",
    "category": "Activity",
    "color": "hsl(168, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "morning_watches",
    "target": 1
  },
  {
    "id": "ach_37",
    "name": "Early Bird II",
    "description": "Reach 5 items logged between 5 am and 9 am.",
    "icon": "Sun",
    "category": "Activity",
    "color": "hsl(168, 80%, 60%)",
    "score": 50,
    "maxProgress": 5,
    "conditionType": "morning_watches",
    "target": 5
  },
  {
    "id": "ach_38",
    "name": "Early Bird III",
    "description": "Reach 15 items logged between 5 am and 9 am.",
    "icon": "Sun",
    "category": "Activity",
    "color": "hsl(168, 80%, 60%)",
    "score": 150,
    "maxProgress": 15,
    "conditionType": "morning_watches",
    "target": 15
  },
  {
    "id": "ach_39",
    "name": "Early Bird IV",
    "description": "Reach 30 items logged between 5 am and 9 am.",
    "icon": "Sun",
    "category": "Activity",
    "color": "hsl(168, 80%, 60%)",
    "score": 500,
    "maxProgress": 30,
    "conditionType": "morning_watches",
    "target": 30
  },
  {
    "id": "ach_40",
    "name": "Early Bird V",
    "description": "Reach 50 items logged between 5 am and 9 am.",
    "icon": "Sun",
    "category": "Activity",
    "color": "hsl(168, 80%, 60%)",
    "score": 1500,
    "maxProgress": 50,
    "conditionType": "morning_watches",
    "target": 50
  },
  {
    "id": "ach_41",
    "name": "Weekend Warrior I",
    "description": "Reach 1 items logged on weekends.",
    "icon": "Calendar",
    "category": "Activity",
    "color": "hsl(192, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "weekend_watches",
    "target": 1
  },
  {
    "id": "ach_42",
    "name": "Weekend Warrior II",
    "description": "Reach 10 items logged on weekends.",
    "icon": "Calendar",
    "category": "Activity",
    "color": "hsl(192, 80%, 60%)",
    "score": 50,
    "maxProgress": 10,
    "conditionType": "weekend_watches",
    "target": 10
  },
  {
    "id": "ach_43",
    "name": "Weekend Warrior III",
    "description": "Reach 25 items logged on weekends.",
    "icon": "Calendar",
    "category": "Activity",
    "color": "hsl(192, 80%, 60%)",
    "score": 150,
    "maxProgress": 25,
    "conditionType": "weekend_watches",
    "target": 25
  },
  {
    "id": "ach_44",
    "name": "Weekend Warrior IV",
    "description": "Reach 50 items logged on weekends.",
    "icon": "Calendar",
    "category": "Activity",
    "color": "hsl(192, 80%, 60%)",
    "score": 500,
    "maxProgress": 50,
    "conditionType": "weekend_watches",
    "target": 50
  },
  {
    "id": "ach_45",
    "name": "Weekend Warrior V",
    "description": "Reach 100 items logged on weekends.",
    "icon": "Calendar",
    "category": "Activity",
    "color": "hsl(192, 80%, 60%)",
    "score": 1500,
    "maxProgress": 100,
    "conditionType": "weekend_watches",
    "target": 100
  },
  {
    "id": "ach_46",
    "name": "Binge Watcher I",
    "description": "Reach 3 items logged on the exact same day.",
    "icon": "Zap",
    "category": "Activity",
    "color": "hsl(216, 80%, 60%)",
    "score": 10,
    "maxProgress": 3,
    "conditionType": "max_in_one_day",
    "target": 3
  },
  {
    "id": "ach_47",
    "name": "Binge Watcher II",
    "description": "Reach 5 items logged on the exact same day.",
    "icon": "Zap",
    "category": "Activity",
    "color": "hsl(216, 80%, 60%)",
    "score": 50,
    "maxProgress": 5,
    "conditionType": "max_in_one_day",
    "target": 5
  },
  {
    "id": "ach_48",
    "name": "Binge Watcher III",
    "description": "Reach 7 items logged on the exact same day.",
    "icon": "Zap",
    "category": "Activity",
    "color": "hsl(216, 80%, 60%)",
    "score": 150,
    "maxProgress": 7,
    "conditionType": "max_in_one_day",
    "target": 7
  },
  {
    "id": "ach_49",
    "name": "Binge Watcher IV",
    "description": "Reach 10 items logged on the exact same day.",
    "icon": "Zap",
    "category": "Activity",
    "color": "hsl(216, 80%, 60%)",
    "score": 500,
    "maxProgress": 10,
    "conditionType": "max_in_one_day",
    "target": 10
  },
  {
    "id": "ach_50",
    "name": "Binge Watcher V",
    "description": "Reach 15 items logged on the exact same day.",
    "icon": "Zap",
    "category": "Activity",
    "color": "hsl(216, 80%, 60%)",
    "score": 1500,
    "maxProgress": 15,
    "conditionType": "max_in_one_day",
    "target": 15
  },
  {
    "id": "ach_51",
    "name": "The Planner I",
    "description": "Reach 1 items added to watchlist.",
    "icon": "List",
    "category": "Collections & Lists",
    "color": "hsl(240, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "watchlist_count",
    "target": 1
  },
  {
    "id": "ach_52",
    "name": "The Planner II",
    "description": "Reach 10 items added to watchlist.",
    "icon": "List",
    "category": "Collections & Lists",
    "color": "hsl(240, 80%, 60%)",
    "score": 50,
    "maxProgress": 10,
    "conditionType": "watchlist_count",
    "target": 10
  },
  {
    "id": "ach_53",
    "name": "The Planner III",
    "description": "Reach 50 items added to watchlist.",
    "icon": "List",
    "category": "Collections & Lists",
    "color": "hsl(240, 80%, 60%)",
    "score": 150,
    "maxProgress": 50,
    "conditionType": "watchlist_count",
    "target": 50
  },
  {
    "id": "ach_54",
    "name": "The Planner IV",
    "description": "Reach 100 items added to watchlist.",
    "icon": "List",
    "category": "Collections & Lists",
    "color": "hsl(240, 80%, 60%)",
    "score": 500,
    "maxProgress": 100,
    "conditionType": "watchlist_count",
    "target": 100
  },
  {
    "id": "ach_55",
    "name": "The Planner V",
    "description": "Reach 250 items added to watchlist.",
    "icon": "List",
    "category": "Collections & Lists",
    "color": "hsl(240, 80%, 60%)",
    "score": 1500,
    "maxProgress": 250,
    "conditionType": "watchlist_count",
    "target": 250
  },
  {
    "id": "ach_56",
    "name": "Curator I",
    "description": "Reach 1 items marked as favorite.",
    "icon": "Star",
    "category": "Collections & Lists",
    "color": "hsl(264, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "favorites_count",
    "target": 1
  },
  {
    "id": "ach_57",
    "name": "Curator II",
    "description": "Reach 5 items marked as favorite.",
    "icon": "Star",
    "category": "Collections & Lists",
    "color": "hsl(264, 80%, 60%)",
    "score": 50,
    "maxProgress": 5,
    "conditionType": "favorites_count",
    "target": 5
  },
  {
    "id": "ach_58",
    "name": "Curator III",
    "description": "Reach 10 items marked as favorite.",
    "icon": "Star",
    "category": "Collections & Lists",
    "color": "hsl(264, 80%, 60%)",
    "score": 150,
    "maxProgress": 10,
    "conditionType": "favorites_count",
    "target": 10
  },
  {
    "id": "ach_59",
    "name": "Curator IV",
    "description": "Reach 25 items marked as favorite.",
    "icon": "Star",
    "category": "Collections & Lists",
    "color": "hsl(264, 80%, 60%)",
    "score": 500,
    "maxProgress": 25,
    "conditionType": "favorites_count",
    "target": 25
  },
  {
    "id": "ach_60",
    "name": "Curator V",
    "description": "Reach 50 items marked as favorite.",
    "icon": "Star",
    "category": "Collections & Lists",
    "color": "hsl(264, 80%, 60%)",
    "score": 1500,
    "maxProgress": 50,
    "conditionType": "favorites_count",
    "target": 50
  },
  {
    "id": "ach_61",
    "name": "Serial Binger I",
    "description": "Reach 10 individual tv episodes watched.",
    "icon": "MonitorPlay",
    "category": "Milestones",
    "color": "hsl(288, 80%, 60%)",
    "score": 10,
    "maxProgress": 10,
    "conditionType": "episodes_watched",
    "target": 10
  },
  {
    "id": "ach_62",
    "name": "Serial Binger II",
    "description": "Reach 50 individual tv episodes watched.",
    "icon": "MonitorPlay",
    "category": "Milestones",
    "color": "hsl(288, 80%, 60%)",
    "score": 50,
    "maxProgress": 50,
    "conditionType": "episodes_watched",
    "target": 50
  },
  {
    "id": "ach_63",
    "name": "Serial Binger III",
    "description": "Reach 100 individual tv episodes watched.",
    "icon": "MonitorPlay",
    "category": "Milestones",
    "color": "hsl(288, 80%, 60%)",
    "score": 150,
    "maxProgress": 100,
    "conditionType": "episodes_watched",
    "target": 100
  },
  {
    "id": "ach_64",
    "name": "Serial Binger IV",
    "description": "Reach 250 individual tv episodes watched.",
    "icon": "MonitorPlay",
    "category": "Milestones",
    "color": "hsl(288, 80%, 60%)",
    "score": 500,
    "maxProgress": 250,
    "conditionType": "episodes_watched",
    "target": 250
  },
  {
    "id": "ach_65",
    "name": "Serial Binger V",
    "description": "Reach 500 individual tv episodes watched.",
    "icon": "MonitorPlay",
    "category": "Milestones",
    "color": "hsl(288, 80%, 60%)",
    "score": 1500,
    "maxProgress": 500,
    "conditionType": "episodes_watched",
    "target": 500
  },
  {
    "id": "ach_66",
    "name": "The Archivist I",
    "description": "Reach 1 custom collections created.",
    "icon": "Folder",
    "category": "Collections & Lists",
    "color": "hsl(312, 80%, 60%)",
    "score": 10,
    "maxProgress": 1,
    "conditionType": "collections_created",
    "target": 1
  },
  {
    "id": "ach_67",
    "name": "The Archivist II",
    "description": "Reach 3 custom collections created.",
    "icon": "Folder",
    "category": "Collections & Lists",
    "color": "hsl(312, 80%, 60%)",
    "score": 50,
    "maxProgress": 3,
    "conditionType": "collections_created",
    "target": 3
  },
  {
    "id": "ach_68",
    "name": "The Archivist III",
    "description": "Reach 5 custom collections created.",
    "icon": "Folder",
    "category": "Collections & Lists",
    "color": "hsl(312, 80%, 60%)",
    "score": 150,
    "maxProgress": 5,
    "conditionType": "collections_created",
    "target": 5
  },
  {
    "id": "ach_69",
    "name": "The Archivist IV",
    "description": "Reach 10 custom collections created.",
    "icon": "Folder",
    "category": "Collections & Lists",
    "color": "hsl(312, 80%, 60%)",
    "score": 500,
    "maxProgress": 10,
    "conditionType": "collections_created",
    "target": 10
  },
  {
    "id": "ach_70",
    "name": "The Archivist V",
    "description": "Reach 20 custom collections created.",
    "icon": "Folder",
    "category": "Collections & Lists",
    "color": "hsl(312, 80%, 60%)",
    "score": 1500,
    "maxProgress": 20,
    "conditionType": "collections_created",
    "target": 20
  },
  {
    "id": "ach_71",
    "name": "Librarian I",
    "description": "Reach 10 items added to collections.",
    "icon": "Library",
    "category": "Collections & Lists",
    "color": "hsl(336, 80%, 60%)",
    "score": 10,
    "maxProgress": 10,
    "conditionType": "collection_items",
    "target": 10
  },
  {
    "id": "ach_72",
    "name": "Librarian II",
    "description": "Reach 50 items added to collections.",
    "icon": "Library",
    "category": "Collections & Lists",
    "color": "hsl(336, 80%, 60%)",
    "score": 50,
    "maxProgress": 50,
    "conditionType": "collection_items",
    "target": 50
  },
  {
    "id": "ach_73",
    "name": "Librarian III",
    "description": "Reach 100 items added to collections.",
    "icon": "Library",
    "category": "Collections & Lists",
    "color": "hsl(336, 80%, 60%)",
    "score": 150,
    "maxProgress": 100,
    "conditionType": "collection_items",
    "target": 100
  },
  {
    "id": "ach_74",
    "name": "Librarian IV",
    "description": "Reach 200 items added to collections.",
    "icon": "Library",
    "category": "Collections & Lists",
    "color": "hsl(336, 80%, 60%)",
    "score": 500,
    "maxProgress": 200,
    "conditionType": "collection_items",
    "target": 200
  },
  {
    "id": "ach_75",
    "name": "Librarian V",
    "description": "Reach 500 items added to collections.",
    "icon": "Library",
    "category": "Collections & Lists",
    "color": "hsl(336, 80%, 60%)",
    "score": 1500,
    "maxProgress": 500,
    "conditionType": "collection_items",
    "target": 500
  },
  {
    "id": "ach_76",
    "name": "Cinema Legend I",
    "description": "Reach 500 total watches.",
    "icon": "Award",
    "category": "Cinema Legend",
    "color": "hsl(50, 100%, 50%)",
    "score": 5000,
    "maxProgress": 500,
    "conditionType": "total_watches",
    "target": 500
  },
  {
    "id": "ach_77",
    "name": "Cinema Legend II",
    "description": "Reach 1000 total watches.",
    "icon": "Award",
    "category": "Cinema Legend",
    "color": "hsl(50, 100%, 50%)",
    "score": 5000,
    "maxProgress": 1000,
    "conditionType": "total_watches",
    "target": 1000
  },
  {
    "id": "ach_78",
    "name": "Cinema Legend III",
    "description": "Reach 1500 total watches.",
    "icon": "Award",
    "category": "Cinema Legend",
    "color": "hsl(50, 100%, 50%)",
    "score": 5000,
    "maxProgress": 1500,
    "conditionType": "total_watches",
    "target": 1500
  },
  {
    "id": "ach_79",
    "name": "Cinema Legend IV",
    "description": "Reach 2000 total watches.",
    "icon": "Award",
    "category": "Cinema Legend",
    "color": "hsl(50, 100%, 50%)",
    "score": 5000,
    "maxProgress": 2000,
    "conditionType": "total_watches",
    "target": 2000
  },
  {
    "id": "ach_80",
    "name": "Cinema Legend V",
    "description": "Reach 2500 total watches.",
    "icon": "Award",
    "category": "Cinema Legend",
    "color": "hsl(50, 100%, 50%)",
    "score": 5000,
    "maxProgress": 2500,
    "conditionType": "total_watches",
    "target": 2500
  },
  {
    "id": "ach_81",
    "name": "Point Hoarder I",
    "description": "Reach a total achievement score of 2000.",
    "icon": "Crown",
    "category": "Cinema Legend",
    "color": "hsl(300, 100%, 70%)",
    "score": 1000,
    "maxProgress": 2000,
    "conditionType": "total_score",
    "target": 2000
  },
  {
    "id": "ach_82",
    "name": "Point Hoarder II",
    "description": "Reach a total achievement score of 4000.",
    "icon": "Crown",
    "category": "Cinema Legend",
    "color": "hsl(300, 100%, 70%)",
    "score": 1000,
    "maxProgress": 4000,
    "conditionType": "total_score",
    "target": 4000
  },
  {
    "id": "ach_83",
    "name": "Point Hoarder III",
    "description": "Reach a total achievement score of 6000.",
    "icon": "Crown",
    "category": "Cinema Legend",
    "color": "hsl(300, 100%, 70%)",
    "score": 1000,
    "maxProgress": 6000,
    "conditionType": "total_score",
    "target": 6000
  },
  {
    "id": "ach_84",
    "name": "Point Hoarder IV",
    "description": "Reach a total achievement score of 8000.",
    "icon": "Crown",
    "category": "Cinema Legend",
    "color": "hsl(300, 100%, 70%)",
    "score": 1000,
    "maxProgress": 8000,
    "conditionType": "total_score",
    "target": 8000
  },
  {
    "id": "ach_85",
    "name": "Point Hoarder V",
    "description": "Reach a total achievement score of 10000.",
    "icon": "Crown",
    "category": "Cinema Legend",
    "color": "hsl(300, 100%, 70%)",
    "score": 1000,
    "maxProgress": 10000,
    "conditionType": "total_score",
    "target": 10000
  },
  {
    "id": "ach_86",
    "name": "Point Hoarder VI",
    "description": "Reach a total achievement score of 12000.",
    "icon": "Crown",
    "category": "Cinema Legend",
    "color": "hsl(300, 100%, 70%)",
    "score": 1000,
    "maxProgress": 12000,
    "conditionType": "total_score",
    "target": 12000
  },
  {
    "id": "ach_87",
    "name": "Point Hoarder VII",
    "description": "Reach a total achievement score of 14000.",
    "icon": "Crown",
    "category": "Cinema Legend",
    "color": "hsl(300, 100%, 70%)",
    "score": 1000,
    "maxProgress": 14000,
    "conditionType": "total_score",
    "target": 14000
  },
  {
    "id": "ach_88",
    "name": "Point Hoarder VIII",
    "description": "Reach a total achievement score of 16000.",
    "icon": "Crown",
    "category": "Cinema Legend",
    "color": "hsl(300, 100%, 70%)",
    "score": 1000,
    "maxProgress": 16000,
    "conditionType": "total_score",
    "target": 16000
  },
  {
    "id": "ach_89",
    "name": "Point Hoarder IX",
    "description": "Reach a total achievement score of 18000.",
    "icon": "Crown",
    "category": "Cinema Legend",
    "color": "hsl(300, 100%, 70%)",
    "score": 1000,
    "maxProgress": 18000,
    "conditionType": "total_score",
    "target": 18000
  },
  {
    "id": "ach_90",
    "name": "Point Hoarder X",
    "description": "Reach a total achievement score of 20000.",
    "icon": "Crown",
    "category": "Cinema Legend",
    "color": "hsl(300, 100%, 70%)",
    "score": 1000,
    "maxProgress": 20000,
    "conditionType": "total_score",
    "target": 20000
  }
,
  {
    "id": "ach_101",
    "name": "Action Hero",
    "description": "Log 10 Action movies.",
    "icon": "Zap",
    "category": "Genres",
    "color": "hsl(0, 80%, 50%)",
    "score": 50,
    "maxProgress": 10,
    "conditionType": "genre_action",
    "target": 10
  },
  {
    "id": "ach_102",
    "name": "Action Master",
    "description": "Log 50 Action movies.",
    "icon": "Zap",
    "category": "Genres",
    "color": "hsl(0, 80%, 50%)",
    "score": 200,
    "maxProgress": 50,
    "conditionType": "genre_action",
    "target": 50
  },
  {
    "id": "ach_103",
    "name": "Horror Fanatic",
    "description": "Log 10 Horror movies.",
    "icon": "Ghost",
    "category": "Genres",
    "color": "hsl(300, 80%, 30%)",
    "score": 50,
    "maxProgress": 10,
    "conditionType": "genre_horror",
    "target": 10
  },
  {
    "id": "ach_104",
    "name": "Scream Expert",
    "description": "Log 50 Horror movies.",
    "icon": "Ghost",
    "category": "Genres",
    "color": "hsl(300, 80%, 30%)",
    "score": 200,
    "maxProgress": 50,
    "conditionType": "genre_horror",
    "target": 50
  },
  {
    "id": "ach_105",
    "name": "Sci-Fi Explorer",
    "description": "Log 10 Sci-Fi movies.",
    "icon": "Rocket",
    "category": "Genres",
    "color": "hsl(210, 80%, 60%)",
    "score": 50,
    "maxProgress": 10,
    "conditionType": "genre_scifi",
    "target": 10
  },
  {
    "id": "ach_106",
    "name": "Sci-Fi Voyager",
    "description": "Log 50 Sci-Fi movies.",
    "icon": "Rocket",
    "category": "Genres",
    "color": "hsl(210, 80%, 60%)",
    "score": 200,
    "maxProgress": 50,
    "conditionType": "genre_scifi",
    "target": 50
  },
  {
    "id": "ach_107",
    "name": "Comedy Relief",
    "description": "Log 10 Comedy movies.",
    "icon": "Smile",
    "category": "Genres",
    "color": "hsl(60, 80%, 50%)",
    "score": 50,
    "maxProgress": 10,
    "conditionType": "genre_comedy",
    "target": 10
  },
  {
    "id": "ach_108",
    "name": "Stand-up Star",
    "description": "Log 50 Comedy movies.",
    "icon": "Smile",
    "category": "Genres",
    "color": "hsl(60, 80%, 50%)",
    "score": 200,
    "maxProgress": 50,
    "conditionType": "genre_comedy",
    "target": 50
  },
  {
    "id": "ach_109",
    "name": "Time Traveler",
    "description": "Log 5 movies released before 1980.",
    "icon": "Clock",
    "category": "Exploration",
    "color": "hsl(30, 80%, 50%)",
    "score": 100,
    "maxProgress": 5,
    "conditionType": "old_movies",
    "target": 5
  },
  {
    "id": "ach_110",
    "name": "Historian",
    "description": "Log 20 movies released before 1980.",
    "icon": "Clock",
    "category": "Exploration",
    "color": "hsl(30, 80%, 50%)",
    "score": 300,
    "maxProgress": 20,
    "conditionType": "old_movies",
    "target": 20
  },
  {
    "id": "ach_111",
    "name": "Marathon Runner",
    "description": "Log 5 movies over 3 hours long.",
    "icon": "Activity",
    "category": "Exploration",
    "color": "hsl(0, 0%, 50%)",
    "score": 100,
    "maxProgress": 5,
    "conditionType": "long_runtime",
    "target": 5
  },
  {
    "id": "ach_112",
    "name": "Endurance Champion",
    "description": "Log 20 movies over 3 hours long.",
    "icon": "Activity",
    "category": "Exploration",
    "color": "hsl(0, 0%, 50%)",
    "score": 300,
    "maxProgress": 20,
    "conditionType": "long_runtime",
    "target": 20
  },
  {
    "id": "ach_113",
    "name": "Short & Sweet",
    "description": "Log 10 movies under 90 minutes.",
    "icon": "FastForward",
    "category": "Exploration",
    "color": "hsl(180, 80%, 40%)",
    "score": 50,
    "maxProgress": 10,
    "conditionType": "short_runtime",
    "target": 10
  },
  {
    "id": "ach_114",
    "name": "Quick Bites",
    "description": "Log 50 movies under 90 minutes.",
    "icon": "FastForward",
    "category": "Exploration",
    "color": "hsl(180, 80%, 40%)",
    "score": 200,
    "maxProgress": 50,
    "conditionType": "short_runtime",
    "target": 50
  },
  {
    "id": "ach_115",
    "name": "Goodfella",
    "description": "Complete the Martin Scorsese Director Journey.",
    "icon": "Award",
    "category": "Director Journeys",
    "color": "hsl(10, 80%, 40%)",
    "score": 1000,
    "maxProgress": 15,
    "conditionType": "dir_scorsese",
    "target": 15
  },
  {
    "id": "ach_116",
    "name": "Perfectionist",
    "description": "Complete the David Fincher Director Journey.",
    "icon": "Award",
    "category": "Director Journeys",
    "color": "hsl(150, 80%, 30%)",
    "score": 1000,
    "maxProgress": 10,
    "conditionType": "dir_fincher",
    "target": 10
  },
  {
    "id": "ach_117",
    "name": "Dune Walker",
    "description": "Complete the Denis Villeneuve Director Journey.",
    "icon": "Award",
    "category": "Director Journeys",
    "color": "hsl(30, 80%, 60%)",
    "score": 1000,
    "maxProgress": 8,
    "conditionType": "dir_villeneuve",
    "target": 8
  },
  {
    "id": "ach_118",
    "name": "Symmetrical",
    "description": "Complete the Wes Anderson Director Journey.",
    "icon": "Award",
    "category": "Director Journeys",
    "color": "hsl(330, 80%, 70%)",
    "score": 1000,
    "maxProgress": 10,
    "conditionType": "dir_anderson",
    "target": 10
  },
  {
    "id": "ach_119",
    "name": "Perfect Week",
    "description": "Log at least one item every day for 7 days.",
    "icon": "Calendar",
    "category": "Streaks",
    "color": "hsl(45, 100%, 50%)",
    "score": 200,
    "maxProgress": 7,
    "conditionType": "streak_7_days",
    "target": 7
  },
  {
    "id": "ach_120",
    "name": "Unstoppable",
    "description": "Log at least one item every day for 30 days.",
    "icon": "Calendar",
    "category": "Streaks",
    "color": "hsl(45, 100%, 50%)",
    "score": 1000,
    "maxProgress": 30,
    "conditionType": "streak_30_days",
    "target": 30
  },
  {
    "id": "ach_121",
    "name": "Rewatch Addict",
    "description": "Log 5 items that you have already watched.",
    "icon": "Repeat",
    "category": "Activity",
    "color": "hsl(270, 80%, 60%)",
    "score": 100,
    "maxProgress": 5,
    "conditionType": "rewatches",
    "target": 5
  },
  {
    "id": "ach_122",
    "name": "Déjà Vu",
    "description": "Log 20 items that you have already watched.",
    "icon": "Repeat",
    "category": "Activity",
    "color": "hsl(270, 80%, 60%)",
    "score": 400,
    "maxProgress": 20,
    "conditionType": "rewatches",
    "target": 20
  },
  {
    "id": "ach_123",
    "name": "Social Butterfly",
    "description": "Follow 10 other users.",
    "icon": "Users",
    "category": "Social",
    "color": "hsl(200, 80%, 50%)",
    "score": 100,
    "maxProgress": 10,
    "conditionType": "following_count",
    "target": 10
  },
  {
    "id": "ach_124",
    "name": "Influencer",
    "description": "Gain 50 followers.",
    "icon": "UserPlus",
    "category": "Social",
    "color": "hsl(340, 80%, 60%)",
    "score": 500,
    "maxProgress": 50,
    "conditionType": "followers_count",
    "target": 50
  },
  {
    "id": "ach_125",
    "name": "Completionist",
    "description": "Reach a total achievement score of 10,000.",
    "icon": "Trophy",
    "category": "Completionist",
    "color": "hsl(55, 100%, 50%)",
    "score": 0,
    "maxProgress": 10000,
    "conditionType": "total_score",
    "target": 10000
  },
  {
    "id": "ach_mcu",
    "name": "Marvel",
    "description": "Complete the Cinematic Universe (Infinity Saga).",
    "icon": "ach_marvel.png",
    "category": "Collections",
    "color": "hsl(0, 80%, 60%)",
    "score": 1000,
    "maxProgress": 23,
    "conditionType": "col_mcu",
    "target": 23
  },
  {
    "id": "ach_hp",
    "name": "Harry Potter",
    "description": "Complete the Complete Collection.",
    "icon": "ach_hp.png",
    "category": "Collections",
    "color": "hsl(40, 80%, 50%)",
    "score": 1000,
    "maxProgress": 8,
    "conditionType": "col_hp",
    "target": 8
  },
  {
    "id": "ach_dark_knight",
    "name": "The Dark Knight",
    "description": "Complete the Trilogy.",
    "icon": "ach_batman.png",
    "category": "Collections",
    "color": "hsl(220, 80%, 60%)",
    "score": 500,
    "maxProgress": 3,
    "conditionType": "col_dark_knight",
    "target": 3
  },
  {
    "id": "ach_ghibli",
    "name": "Studio Ghibli",
    "description": "Complete the Essentials.",
    "icon": "ach_ghibli.png",
    "category": "Collections",
    "color": "hsl(200, 80%, 60%)",
    "score": 1000,
    "maxProgress": 10,
    "conditionType": "col_ghibli",
    "target": 10
  }
];

export function getAllAchievements(): Achievement[] {
  return ACHIEVEMENTS;
}

export function getAchievement(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find(a => a.id === id);
}
